# Generated by Django 5.1.4 on 2024-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Користувач з такою адресою електронної пошти вже існує"
                },
                max_length=254,
                verbose_name="Адреса електронної пошти",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("email",), name="user_email_unique_constraint"
            ),
        ),
    ]
