# Generated by Django 5.1.4 on 2024-12-13 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Назва категорії"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис категорії"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата останньої зміни"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        related_query_name="child",
                        to="inventory.materialcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія матеріалу",
                "verbose_name_plural": "Категорії матеріалів",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва матеріалу"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис матеріалу"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість на складі"
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна за одиницю"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="Зображення матеріалу",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата останньої зміни"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        related_query_name="material",
                        to="inventory.materialcategory",
                        verbose_name="Категорія матеріалу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матеріал",
                "verbose_name_plural": "Матеріали",
            },
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(fields=["name"], name="material_category_name_index"),
        ),
    ]
