# Generated by Django 5.1.4 on 2024-12-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=("name",), name="material_unique_name_constraint"
            ),
        ),
    ]
