# Generated by Django 5.1.4 on 2024-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_material_material_unique_name_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialcategory",
            name="parent",
        ),
        migrations.AlterField(
            model_name="materialcategory",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Категорія з такою назвою вже існує"},
                max_length=255,
                unique=True,
                verbose_name="Назва категорії",
            ),
        ),
    ]
