# Generated by Django 5.1.4 on 2024-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_remove_materialcategory_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Назва матеріалу"
            ),
        ),
    ]
