# Generated by Django 5.1.4 on 2024-12-16 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_orderitem_price_per_unit_alter_orderitem_material"),
        ("inventory", "0004_alter_material_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзини",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderitems",
                related_query_name="orderitem",
                to="inventory.material",
                verbose_name="Матеріал",
            ),
        ),
    ]
